[project]
name = "R-AScan"
version = "0.1.1"
description = "Dynamic web security scanner with normalized JSON and HTML reporting"
authors = [
  { name="HarshXor", email="harshxor@incrustwerush.org" }
]
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]
keywords = [
  "security",
  "vulnerability-scanner",
  "web-security",
  "pentesting",
  "owasp",
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Intended Audience :: Information Technology",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Security",
]

dependencies = [
  "requests>=2.25.1",
  "colorama>=0.4.6",
  "beautifulsoup4>=4.12.3"
]

[project.urls]
Homepage = "https://github.com/ICWR-TEAM/R-AScan"
Repository = "https://github.com/ICWR-TEAM/R-AScan"
Issues = "https://github.com/ICWR-TEAM/R-AScan/issues"

[project.scripts]
R-AScan = "r_ascan.app:main"

[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"r_ascan.resources" = ["*.*"]
"r_ascan.module" = ["*.*"]
"r_ascan.scanners" = ["*.*"]

[tool.setuptools.packages.find]
include = ["r_ascan*"]
exclude = ["tests*"]
